apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: argotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
        - name: busybox-container
          image: busybox
          ports:
            - containerPort: 8787
              name: http
              protocol: TCP