apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: argotest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
        - name: busybox
          image: busybox