apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: argotest
  labels:
      name: busybox-deployment
      k8s-object: pod
      app: busybox-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-deployment
      k8s-object: pod
      app: busybox-app
  template:
    metadata:
      labels:
        name: busybox-deployment
        k8s-object: pod
        app: busybox-app
    spec:
      containers:
        - name: busybox
          image: busybox
