apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: argotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox-container
          image: busybox
          command: ["sh", "-c", "while true; do echo 'BusyBox is running'; sleep 10; done"]
