apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-deployment
  namespace: argotest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: redpanda-app
  template:
    metadata:
      labels:
        app: redpanda-app
    spec:
      containers:
        - name: redpanda-container
          image: vectorized/redpanda
          ports:
            - containerPort: 8787
              name: http
              protocol: TCP